### ISSUE TITLE
Download package contains a virus (or is identified as a virus)

### ISSUE THREAD

**Issue by KeithwNZ** [stax76/run-hidden#3]

**Comment by stax76** [comment]
False positive, I would guess.

I've recompiled and re-uploaded it, www.virustotal.com still shows 2 detections, however.

Which antivirus software reported this?

**Comment by KeithwNZ** [comment]
Previous download attempt may have been blocked by organisational security infrastructure ? (which uses HTTPS inspection) - browser download had resulted in "virus detected" - however v1.2 download on personal network is fine.  Both Microsoft AntiMalware and ESET Internet Protection now pass it as clean.
