### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by bjossles** [stax76/run-hidden#6]
Pardon my ignorance of c++.
I am getting the following error when compiling with g++:
\Downloads\run-hidden-master\run-hidden-master\run-hidden.cpp:85:1: warning: no return statement in function returning non-void [-Wreturn-type]   85 | }
      | ^

**Comment by stax76** [comment]
It's only compatible with Visual Studio.

**Comment by bjossles** [comment]
I was using VS Code. I guess you mean the full version.
