### ISSUE TITLE
Usage Help

### ISSUE THREAD

**Issue by yokhoe** [stax76/run-hidden#7]
I have a powershell script that is essentially a systray application.  I want to be able to hide this console window that generates unnecessary output.
![image](https://github.com/stax76/run-hidden/assets/22972701/84f38a96-0d6c-4710-9662-b964a0304349)

How do you utilize run-hidden.exe in this regard?  I've tried a couple of variations.  All in all, the processes seem to run, but not the powershell script itself.
![image](https://github.com/stax76/run-hidden/assets/22972701/531ad305-c647-4339-a5ec-731cb6a90358)
![image](https://github.com/stax76/run-hidden/assets/22972701/2aac7749-be6c-45fd-9ee8-3859dba51015)

**Comment by stax76** [comment]
You can try executing the command line in a terminal, but with run hidden excluded, then see if output appears.

**Comment by yokhoe** [comment]
It does execute in Terminal (granted that the security warning still coming up despite the `-ExecutionPolicy bypass` inclusion :/

**Comment by stax76** [comment]
This warning blocks the script from running, here is your problem, you have to get rid of this warning. The Unblock-File cmdlet might be the right solution, I don't know if there are other solutions.

If you want to run the script on system startup, put the command line into a shortcut (.lnk file) and put the shortcut file into the Startup folder:

C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by yokhoe** [comment]
I think that did it. I was trying to configure it in Task Scheduler to execute at logon.
