### ISSUE TITLE
Run Explorer links directly

### ISSUE THREAD

**Issue by Hexaae** [stax76/run-hidden#8]
Can you add link (.lnk) support to directly launch Windows link files like Explorer.exe does?

**Comment by stax76** [comment]
Windows has two functions to execute applications:

1. CreateProcess can hide applications, but only supports EXE files.
2. ShellExecuteEx supports non EXE files such as .lnk files, but it cannot hide applications.

So no, what you are asking for is technically not possible.

If you tell me what your goal is, I might be able to tell you how you can get it.

**Comment by Hexaae** [comment]
It seems `nircmd.exe execmd <command>` does work fine also with .lnk
https://www.nirsoft.net/utils/nircmd.html
